In [2]:
# Numpy package is designed to work with multi-dimensional arrays, 
# its essentially numerical python, pandas is buit on numpy to make
# numpy easier to use, we have to first import it, we can use an alias 
# while doing so, so that its easier to use than having to type, numpy
# each time
import numpy as np

In [43]:
# create a 2D array

a = np.array([[1, 3, 5, 8],[5, 10, 15, 20],[37, -8, 6, 23],[-5, 63, 27, 4]])
a

array([[ 1,  3,  5,  8],
       [ 5, 10, 15, 20],
       [37, -8,  6, 23],
       [-5, 63, 27,  4]])

In [4]:
# to find the shape of the array, the return value will be 
# the no of rows andno of columns in the 2D array
a.shape

(4, 4)

In [7]:
## to access individual elements of arrays for example 23 use indices
## first row then column
a[2][3]

23

In [8]:
# alternate way of doing this
a[2,3]

23

In [17]:
# slicing the array is similar to slicing strings
# if we want the second element from all the lists
print(a)
a[:,1]

[[ 1  3  5  8]
 [ 5 10 15 20]
 [37 -8  6 23]
 [-5 63 27  4]]


array([ 3, 10, -8, 63])

In [18]:
# or accessing the 2nd row from the array
a[1,:]

array([ 5, 10, 15, 20])

In [19]:
# alternate way of accessing an entire row
a[1]

array([ 5, 10, 15, 20])

In [21]:
## accessing multiple elements at the same time
# first [] to access the row index second [] to access the corresponding column

a[[0,1,2,3],[0,1,2,3]]

array([ 1, 10,  6,  4])

In [23]:
# this can also be used to update values in an array
a[0,0] = 0
# or
a[[1,2,3],[1,2,3]] = [1, 2, 3]
print(a)

[[ 0  3  5  8]
 [ 5  1 15 20]
 [37 -8  2 23]
 [-5 63 27  3]]


In [25]:
# subset an array using conditions 
# check whether all the items fulfill a condition
a > 0

array([[False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False,  True,  True],
       [False,  True,  True,  True]])

In [26]:
# or we can use a condition to print those values
# # subset an array using conditions , ie. get the items of the array if 
a[a>0]

array([ 3,  5,  8,  5,  1, 15, 20, 37,  2, 23, 63, 27,  3])

In [44]:
# if we want to check only a particular list(row)
print(a)
a[3]>0

[[ 1  3  5  8]
 [ 5 10 15 20]
 [37 -8  6 23]
 [-5 63 27  4]]


array([False,  True,  True,  True])

In [107]:
# subsetting using the above condition will return the actual values 
a[3,a[3]>0]

array([63, 27,  4])

In [115]:
# getting values from all the lists only for those indices where values
# in the third list were either positive or zero
# seems to get rid of all the columns from each row
print(a[2]>=0)
print(a[:,a[2]>=0])

[ True False  True  True]
[[ 1  5  8]
 [ 5 15 20]
 [37  6 23]
 [-5 27  4]]


In [122]:
# chechking if the third element in each list is positive or no
# it will have as many elements as no of lists
print(a)
print(a[:,2])
print(a[:,2]>0)
a[a[:,2]>0,:]


[[ 1  3  5  8]
 [ 5 10 15 20]
 [37 -8  6 23]
 [-5 63 27  4]]
[ 5 15  6 27]
[ True  True  True  True]


array([[ 1,  3,  5,  8],
       [ 5, 10, 15, 20],
       [37, -8,  6, 23],
       [-5, 63, 27,  4]])

In [116]:
# replacing the entire 2nd row  with their absolute values
# the exponential function in math package  returns the exponential values

import math as m

# exp(0 returns the exponential value of the no passed into it)
x = -80
m.exp(x)


1.8048513878454153e-35

In [118]:
# the exp() from math only works on scalar (single) values
# arrays have multiple values and therefore exp throws up an error
# numpy allows exp values of arrays, the foll returns the exp values of the second list
print(a)
b = np.exp(a[1])
print(b)

[[ 1  3  5  8]
 [ 5 10 15 20]
 [37 -8  6 23]
 [-5 63 27  4]]
[1.48413159e+02 2.20264658e+04 3.26901737e+06 4.85165195e+08]


In [119]:
# arange function returns an array of n no of items from the given start point
np.arange(0,6) # this will return an array of length 5 starting from 0


array([0, 1, 2, 3, 4, 5])

In [120]:
# this will return an array of length 6 starting from 2
np.arange(2,8) 


array([2, 3, 4, 5, 6, 7])

In [9]:
# using linspace - we get the number of parts between two numbers
# backgrounf formula used = (stop-start)/(num-1)
np.linspace(start=1, stop=10, num=10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [10]:
np.linspace(start=2, stop=5, num=8)

array([2.        , 2.42857143, 2.85714286, 3.28571429, 3.71428571,
       4.14285714, 4.57142857, 5.        ])

In [105]:
np.linspace(start=5, stop=2, num=8)

array([5.        , 4.57142857, 4.14285714, 3.71428571, 3.28571429,
       2.85714286, 2.42857143, 2.        ])

In [11]:
np.linspace(start=3, stop=9, num=10)

array([3.        , 3.66666667, 4.33333333, 5.        , 5.66666667,
       6.33333333, 7.        , 7.66666667, 8.33333333, 9.        ])

In [2]:
import random

In [6]:
# use to generate random array items giving high and low values
# size is the size of array wwe want, no of rows and cols
np.random.randint(high=15, low=3, size=(1,1))

array([[11]])

In [20]:
# use to generate random array items giving high and low values
np.random.randint(high=15, low=3, size=(2,2))

array([[ 4,  7],
       [13,  3]])

In [11]:
# seed can be used to give a starting point for the no generation
np.random.seed(10)
np.random.random(size=(2,2))

array([[0.78161516, 0.82893637],
       [0.47359974, 0.46710691]])

In [19]:
# if we use the same seed we will get the same values if executed in the same cell 
# else it will be different
np.random.seed(10)
np.random.random(size=(3,3))

array([[0.15339806, 0.15368441, 0.63341274],
       [0.17385202, 0.04733491, 0.13953703],
       [0.98890883, 0.87546577, 0.22097463]])

In [17]:
# if we use the random package and give it the same seed it will give us the 
# same random number
random.seed(10)
print(random.random())
random.seed(10)
print(random.random())

0.5714025946899135
0.5714025946899135


In [24]:
# if we want to choose a random number from an exixting populated array
# for example a lottery
# using a range to generate an array
b = np.arange(1,10)
b
# choosing a random no from the above b array
np.random.choice(b)

7

In [ ]:
# we can ensure that the same number is never picked twice
np.random.choice(b, replace = False)

In [29]:
# if we want to pick multiple random items like for Housie, we add an argument
np.random.choice(b, 6, replace = False)

array([5, 4, 7, 6, 2, 1])

In [30]:
x = np.arange(1,10)
np.random.choice(x, 6, replace = False)

array([8, 9, 4, 6, 1, 5])

In [35]:
# random choice can be used to simulate data 
# the foll will give me the required elements the necessary no of items
y = np.random.choice(['a','b','c'],10)
y

array(['b', 'c', 'b', 'a', 'c', 'c', 'a', 'a', 'a', 'c'], dtype='<U1')

In [36]:
# in an existing dataset we can use the unique function to see the 
# unique values and the no of times they occur
np.unique(y,return_counts=True)

(array(['a', 'b', 'c'], dtype='<U1'), array([4, 2, 4]))

In [39]:
# we can also specifiy the specific percentage of times each element should occur
z = np.random.choice(['x','y','a'], 15, p=[0.3,0.3,0.4])
print(z)
np.unique(z,return_counts=True)

(array(['a', 'x', 'y'], dtype='<U1'), array([4, 4, 7]))

In [40]:
m = np.random.choice(['x','y','a'], 15, p=[0.5,0.1,0.4])
np.unique(m,return_counts=True)

(array(['a', 'x', 'y'], dtype='<U1'), array([5, 9, 1]))

In [66]:
# sorting elements in an array
# first create a random array of length 10
p = np.random.randint(high=100, low=10, size=(1,10))
print(p)


[[36 65 63 47 59 13 92 32 28 56]]


In [ ]:
# sort works in an ascending order
p_sorted = p.sort()
print(p_sorted) 

In [64]:
# to get it in a descending order
p[::-1]

array([[99, 70, 71, 18, 50, 98, 61, 96, 78, 61]])

In [67]:
# alternate way to sort
sorted(p,reverse=True)

[array([36, 65, 63, 47, 59, 13, 92, 32, 28, 56])]

In [95]:
# using sort for 2D array
arr = np.array([[ 0, 3, 5, 8],[51, 1, 15, 20],[37, -8, 2, 23],[-5, 63, 27, 31]])
print(arr)

[[ 0  3  5  8]
 [51  1 15 20]
 [37 -8  2 23]
 [-5 63 27 31]]


In [96]:
# using sort for a 2D array - it will sort the individual lists(rows) internally

arr.sort()
arr

array([[ 0,  3,  5,  8],
       [ 1, 15, 20, 51],
       [-8,  2, 23, 37],
       [-5, 27, 31, 63]])

In [104]:
arr[:,1].sort()
arr

array([[ 0,  2,  5,  8],
       [ 1,  3, 20, 51],
       [-8, 15, 23, 37],
       [-5, 27, 31, 63]])

In [97]:
# this will sort the columns based on the first value of each list(row) 
arr[::-1]

array([[-5, 27, 31, 63],
       [-8,  2, 23, 37],
       [ 1, 15, 20, 51],
       [ 0,  3,  5,  8]])

In [98]:
# argsort will sort the elements in the array or list and return the indices
print(arr)

[[ 0  3  5  8]
 [ 1 15 20 51]
 [-8  2 23 37]
 [-5 27 31 63]]


In [99]:
# picking the second column argsort will sort the indices
print(arr[:,1])
arr[:,1].argsort()

[ 3 15  2 27]


array([2, 0, 1, 3])

In [101]:
# sorting the required column
arr[arr[:,1].argsort(),:]

array([[-8,  2, 23, 37],
       [ 0,  3,  5,  8],
       [ 1, 15, 20, 51],
       [-5, 27, 31, 63]])

In [103]:
# sorting all the rows using argsort will return indices similar to sort
arr[:,:].argsort()

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [5]:
# Consider an array = [10,20,52,67,100]. Replace all elements which are greater than 50 with 51. Use ndarray and create this

x = np.array([[10,20,52,67,100]])
x[x>50] = 51
print(x)


[[10 20 51 51 51]]


In [7]:
# Suppose we have two matrices A and B. Add these two matrices and also subtract them.
A = [[1,2],[3,4]]
B = [[4,5],[6,7]]

ad = np.add(A,B)
sb = np.subtract(A,B)

print(ad)
print(sb)

[[ 5  7]
 [ 9 11]]
[[-3 -3]
 [-3 -3]]


In [9]:
# For example, for two matrices A and B. Perform matrix multiplication.
A = [[1, 2], [2, 3]]
B = [[4, 5], [6, 7]]

# multiplies elementwise
mul = np.multiply(A,B)

# performs matrix multiplication
mul2 = np.matmul(A,B)

# multiplies scalar matrices, or when the x.shape =! y.shape
mul3 = np.dot(A,B)
print(mul)
print(mul2)
print(mul3)

[[ 4 10]
 [12 21]]
[[16 19]
 [26 31]]
[[16 19]
 [26 31]]


In [3]:
# Count the unique values in this numpy array 
x = np.array([[10, 20, 5, 10, 8, 20, 8, 9]])
np.unique(x,return_counts=True)

(array([ 5,  8,  9, 10, 20]), array([1, 2, 1, 2, 2]))

In [11]:
# Find the common elements between both of them.
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

common = np.intersect1d(a,b)
print(common)

[2 4]


In [57]:
# get all numbers between 5 and 10
a = np.array([2, 6, 1, 9, 10, 3, 27])
sub1 = a[a>5]
sub2 = a[a <10]
common = np.intersect1d(sub1,sub2)

# or 
a[a>5][a[a>5]<10]
print(common)

[6 9]


In [13]:
# Get the positions where elements of a and b match Input:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.argsort(a==b)

## alternative - np.intersect1d(a,b,return_indices=True)

array([0, 2, 4, 6, 8, 9, 1, 3, 5, 7])

In [58]:
# Find the k = 3 smallest numbers in the following array
a = np.array([1,5,3,9,11,14,15])
k = 3

result = np.sort(a)
print(result[:k])

[1 3 5]


In [59]:
# Create a 5X2 integer array from a range between 100 to 200 
# such that the difference between each element is 10
# allows us to generate the required numbers
x = np.arange(100,200,10)

# reshape allows us to reshape the existing data ainto the desired array
x.reshape(5,2)

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [34]:
# Sort the array by the second row and the second column.
arr = np.array([[34,43,73],[82,22,12],[53,94,66]])

print(arr)
arr[arr[1,:].sort()]
arr[arr[:,1].sort(),:]

[[34 43 73]
 [82 22 12]
 [53 94 66]]


array([[[34, 22, 73],
        [12, 43, 82],
        [53, 94, 66]]])

In [67]:
x = np.random.randint(high=100, low=10, size=(1,10))
x

array([[65, 39, 26, 91, 32, 35, 48, 10, 22, 29]])

In [68]:
# returns the minimum element
x.min()

10

In [69]:
# returns the maximum element
x.max()

91

In [70]:
# returns the index of the minimum element
x.argmin()

7

In [71]:
# returns the index of the maximum element
x.argmax()

3

In [ ]:
a = [[1,2,3],[4,5,6]]

In [73]:
# gives sum elementwise
np.sum(a,axis=0)

58

In [ ]:
# gives sum accross the list
np.sum(a,axis=1)

In [78]:
# Find the maximum value in each row of this array 

a = np.array([[2,4,7],[6,31,43],[35,46,23],[6,19,40]])
a.max(axis=1)

array([ 7, 43, 46, 40])

In [84]:
# Add a and b and calculate squares of 
# the resultant matrix and store it in c.
a=[[1,3],[6,9]]
b=[[2,7],[5,8]]

c = np.add(a,b) * np.add(a,b)
c

array([[  9, 100],
       [121, 289]])

In [94]:
# alternate way
x = np.add(a,b)
c = np.power(x,2)
print(c)

[[  9 100]
 [121 289]]


In [93]:
# Create a random vector of size 10 and sort it
z = np.random.randint(high = 100, low = 50, size=(1,10))
print(z)


[[53 89 66 51 90 94 82 56 67 79]]


In [98]:
sorted(z,reverse=True)

[array([53, 89, 66, 51, 90, 94, 82, 56, 67, 79])]

In [103]:
z[::-1]

array([[53, 89, 66, 51, 90, 94, 82, 56, 67, 79]])

In [95]:
# Create a random vector of size 10 and sort it 
np.sort(np.random.random(10))[::-1]

array([0.83333728, 0.67057617, 0.60982168, 0.60112944, 0.48022093,
       0.34986633, 0.32181739, 0.20520895, 0.06345252, 0.01997384])

# Pandas

In [1]:
import numpy as np
import pandas as pd
import random

In [2]:
# create a sample data for dataframe
age = np.random.randint(low = 16, high = 80, size=(20,))
city = np.random.choice(['Mumbai', 'Delhi', 'Bangalore', 'Chennai'], 20)
default = np.random.choice([1,0],20)

In [3]:
# create a tuple using the above values - we can create a df using lists
mydata =list(zip(age,city,default))
mydata

[(40, 'Chennai', 1),
 (64, 'Delhi', 1),
 (38, 'Bangalore', 0),
 (20, 'Bangalore', 0),
 (45, 'Delhi', 1),
 (38, 'Mumbai', 0),
 (28, 'Mumbai', 0),
 (30, 'Chennai', 1),
 (18, 'Delhi', 1),
 (53, 'Mumbai', 1),
 (77, 'Mumbai', 0),
 (26, 'Mumbai', 1),
 (62, 'Delhi', 1),
 (62, 'Delhi', 0),
 (55, 'Bangalore', 0),
 (70, 'Bangalore', 1),
 (50, 'Bangalore', 0),
 (50, 'Mumbai', 1),
 (68, 'Delhi', 1),
 (58, 'Mumbai', 1)]

In [4]:
# create a dataframe using the above - it will create a table
df = pd.DataFrame(mydata, columns = ['age', 'city','default'])
type(df)

pandas.core.frame.DataFrame

In [5]:
# if we want to see only the first 5 rows and not whole frame
df.head()

age       city  default
0   40    Chennai        1
1   64      Delhi        1
2   38  Bangalore        0
3   20  Bangalore        0
4   45      Delhi        1

In [15]:
# we can also create a df using dictionaries 
df = pd.DataFrame({'Age':age, 'City': city, 'Default': default})
df.head()

Age       City  Default
0   44  Bangalore        1
1   38  Bangalore        1
2   39    Chennai        0
3   31      Delhi        1
4   49    Chennai        1

In [4]:
# use r before the path so that data is read as a raw file
file=r'~/Documents/SDBI/Python/digihack.csv'

In [5]:
# read the file and store in the data frame
df1 = pd.read_csv(file)

In [27]:
# use the head function to read the first n rows
df1.head(10)

ID   Age  Customer_type  Gross_income   Net_income      SEX  \
0   1  42.0  SELF EMPLOYED        91,667       91,667     MALE   
1   1  42.0  SELF EMPLOYED        91,667       91,667     MALE   
2   2  38.0       SALARIED      1,50,000       30,000   FEMALE   
3   2  38.0       SALARIED      1,50,000       30,000   FEMALE   
4   3  36.0  SELF EMPLOYED      1,88,183     1,88,183     MALE   
5   3  36.0  SELF EMPLOYED      1,88,183     1,88,183     MALE   
6   4  26.0       SALARIED        15,488       27,000     MALE   
7   4  26.0       SALARIED        15,488       27,000     MALE   
8   5  40.0  SELF EMPLOYED        27,305       27,305     MALE   
9   5  40.0  SELF EMPLOYED        27,305       27,305     MALE   

  Type_of_industry Marital_Status  Months_in_city  Months_in_current_job  ...  \
0     CONSTRUCTION        MARRIED             0.0                     96  ...   
1     CONSTRUCTION        MARRIED             0.0                     96  ...   
2           OTHERS        MARRIED             0.0                    120  ...   
3           OTHERS        MARRIED             0.0                    120  ...   
4           OTHERS        MARRIED             0.0                      0  ...   
5           OTHERS        MARRIED             0.0                      0  ...   
6           OTHERS        MARRIED           324.0                      0  ...   
7           OTHERS        MARRIED           324.0                      0  ...   
8           OTHERS        MARRIED             0.0                    206  ...   
9           OTHERS        MARRIED             0.0                    206  ...   

  ACCOUNT_12  ACCOUNT_13  ACCOUNT_14  ACCOUNT_15  ACCOUNT_16  ACCOUNT_17  \
0         13           0           5           3           0           3   
1         13           0           5           3           0           3   
2          4           0           3           2           0           2   
3          4           0           3           2           0           2   
4         30           2          21           8           1           7   
5         30           2          21           8           1           7   
6          1           0           0           1           0           0   
7          1           0           0           1           0           0   
8          2           0           2           1           0           1   
9          2           0           2           1           0           1   

   ACCOUNT_18  ACCOUNT_19  ACCOUNT_20  ACCOUNT_21  
0     1837374           0     1837374        1657  
1     1837374           0     1837374        1657  
2       10380           0       10380         124  
3       10380           0       10380         124  
4     3445241     1536325     1908916        2534  
5     3445241     1536325     1908916        2534  
6       63566       63566           0         416  
7       63566       63566           0         416  
8       46848           0       46848        2838  
9       46848           0       46848        2838  

[10 rows x 35 columns]

In [28]:
# gives the bottom n rows
df1.tail()

ID   Age  Customer_type  Gross_income   Net_income      SEX  \
3975  3891  28.0       SALARIED        16,090       16,527   FEMALE   
3976  3892  27.0       SALARIED        14,000       23,266     MALE   
3977  3893  43.0  SELF EMPLOYED        21,506       21,506     MALE   
3978  3894  43.0  SELF EMPLOYED             0            0     MALE   
3979  3895  42.0  SELF EMPLOYED             0            0     MALE   

     Type_of_industry Marital_Status  Months_in_city  Months_in_current_job  \
3975           OTHERS        MARRIED             0.0                     36   
3976           OTHERS        MARRIED           324.0                     12   
3977           OTHERS        MARRIED           324.0                     82   
3978           OTHERS        MARRIED           360.0                    142   
3979         TEXTILES        MARRIED           324.0                     14   

      ... ACCOUNT_12  ACCOUNT_13  ACCOUNT_14  ACCOUNT_15  ACCOUNT_16  \
3975  ...          3           0           2           2           0   
3976  ...          3           0           2           3           0   
3977  ...          1           0           0           1           0   
3978  ...         10           0           9           5           0   
3979  ...          6           2           4           4           1   

      ACCOUNT_17  ACCOUNT_18  ACCOUNT_19  ACCOUNT_20  ACCOUNT_21  
3975           1      112907       21754       91153         498  
3976           2       14492           0       14492         995  
3977           0       11285       11285           0         640  
3978           4      601380      554259       47121        1565  
3979           3     1300136     1267864       32272         284  

[5 rows x 35 columns]

In [30]:
# will give us the name of the columns along with the overall data type
df1.columns

Index(['ID', 'Age', 'Customer_type', ' Gross_income ', ' Net_income ', 'SEX',
       'Type_of_industry', 'Marital_Status', 'Months_in_city',
       'Months_in_current_job', 'Org_Type', 'Bank_balance', 'Debt_ratio',
       'Target', 'ENQ_1', 'ENQ_2', 'ENQ_3', 'ENQ_4', 'ENQ_5', 'ENQ_6', 'ENQ_7',
       'ENQ_8', 'ACCOUNT_9', 'ACCOUNT_10', 'ACCOUNT_11', 'ACCOUNT_12',
       'ACCOUNT_13', 'ACCOUNT_14', 'ACCOUNT_15', 'ACCOUNT_16', 'ACCOUNT_17',
       'ACCOUNT_18', 'ACCOUNT_19', 'ACCOUNT_20', 'ACCOUNT_21'],
      dtype='object')

In [31]:
# will give us the data type of the items in the columns
df1.dtypes

ID                         int64
Age                      float64
Customer_type             object
 Gross_income             object
 Net_income               object
SEX                       object
Type_of_industry          object
Marital_Status            object
Months_in_city           float64
Months_in_current_job      int64
Org_Type                  object
Bank_balance             float64
Debt_ratio               float64
Target                     int64
ENQ_1                      int64
ENQ_2                      int64
ENQ_3                      int64
ENQ_4                      int64
ENQ_5                      int64
ENQ_6                      int64
ENQ_7                      int64
ENQ_8                      int64
ACCOUNT_9                  int64
ACCOUNT_10                 int64
ACCOUNT_11                 int64
ACCOUNT_12                 int64
ACCOUNT_13                 int64
ACCOUNT_14                 int64
ACCOUNT_15                 int64
ACCOUNT_16                 int64
ACCOUNT_17

In [32]:
# this gives us the summary/basic info of the data frame incluting null values
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3980 entries, 0 to 3979
Data columns (total 35 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   ID                     3980 non-null   int64  
 1   Age                    3979 non-null   float64
 2   Customer_type          3980 non-null   object 
 3    Gross_income          3980 non-null   object 
 4    Net_income            3980 non-null   object 
 5   SEX                    3976 non-null   object 
 6   Type_of_industry       3975 non-null   object 
 7   Marital_Status         3976 non-null   object 
 8   Months_in_city         3976 non-null   float64
 9   Months_in_current_job  3980 non-null   int64  
 10  Org_Type               3980 non-null   object 
 11  Bank_balance           3344 non-null   float64
 12  Debt_ratio             3980 non-null   float64
 13  Target                 3980 non-null   int64  
 14  ENQ_1                  3980 non-null   int64  
 15  ENQ_

In [33]:
# size of data, no of rows and cols
df1.shape

(3980, 35)

In [37]:
# subsetting data frames on the basis of rows and columns
# iloc is index location with rows and cols
df_sub = df1.iloc[2:7,4:8]
df_sub

Net_income      SEX Type_of_industry Marital_Status
2      30,000   FEMALE           OTHERS        MARRIED
3      30,000   FEMALE           OTHERS        MARRIED
4    1,88,183     MALE           OTHERS        MARRIED
5    1,88,183     MALE           OTHERS        MARRIED
6      27,000     MALE           OTHERS        MARRIED

In [38]:
# we want all rows and n columns
df_sub = df1.iloc[:,4:8]
df_sub

Net_income      SEX Type_of_industry Marital_Status
0         91,667     MALE     CONSTRUCTION        MARRIED
1         91,667     MALE     CONSTRUCTION        MARRIED
2         30,000   FEMALE           OTHERS        MARRIED
3         30,000   FEMALE           OTHERS        MARRIED
4       1,88,183     MALE           OTHERS        MARRIED
...           ...     ...              ...            ...
3975      16,527   FEMALE           OTHERS        MARRIED
3976      23,266     MALE           OTHERS        MARRIED
3977      21,506     MALE           OTHERS        MARRIED
3978           0     MALE           OTHERS        MARRIED
3979           0     MALE         TEXTILES        MARRIED

[3980 rows x 4 columns]

In [39]:
# we want all columns and n rows
df_sub = df1.iloc[2:7,:]
df_sub

ID   Age  Customer_type  Gross_income   Net_income      SEX  \
2   2  38.0       SALARIED      1,50,000       30,000   FEMALE   
3   2  38.0       SALARIED      1,50,000       30,000   FEMALE   
4   3  36.0  SELF EMPLOYED      1,88,183     1,88,183     MALE   
5   3  36.0  SELF EMPLOYED      1,88,183     1,88,183     MALE   
6   4  26.0       SALARIED        15,488       27,000     MALE   

  Type_of_industry Marital_Status  Months_in_city  Months_in_current_job  ...  \
2           OTHERS        MARRIED             0.0                    120  ...   
3           OTHERS        MARRIED             0.0                    120  ...   
4           OTHERS        MARRIED             0.0                      0  ...   
5           OTHERS        MARRIED             0.0                      0  ...   
6           OTHERS        MARRIED           324.0                      0  ...   

  ACCOUNT_12  ACCOUNT_13  ACCOUNT_14  ACCOUNT_15  ACCOUNT_16  ACCOUNT_17  \
2          4           0           3           2           0           2   
3          4           0           3           2           0           2   
4         30           2          21           8           1           7   
5         30           2          21           8           1           7   
6          1           0           0           1           0           0   

   ACCOUNT_18  ACCOUNT_19  ACCOUNT_20  ACCOUNT_21  
2       10380           0       10380         124  
3       10380           0       10380         124  
4     3445241     1536325     1908916        2534  
5     3445241     1536325     1908916        2534  
6       63566       63566           0         416  

[5 rows x 35 columns]

In [41]:
# you can subset the subsetted dataframe as well
df_sub2 = df_sub.iloc[0:2,:]
df_sub2

ID   Age Customer_type  Gross_income   Net_income      SEX  \
2   2  38.0      SALARIED      1,50,000       30,000   FEMALE   
3   2  38.0      SALARIED      1,50,000       30,000   FEMALE   

  Type_of_industry Marital_Status  Months_in_city  Months_in_current_job  ...  \
2           OTHERS        MARRIED             0.0                    120  ...   
3           OTHERS        MARRIED             0.0                    120  ...   

  ACCOUNT_12  ACCOUNT_13  ACCOUNT_14  ACCOUNT_15  ACCOUNT_16  ACCOUNT_17  \
2          4           0           3           2           0           2   
3          4           0           3           2           0           2   

   ACCOUNT_18  ACCOUNT_19  ACCOUNT_20  ACCOUNT_21  
2       10380           0       10380         124  
3       10380           0       10380         124  

[2 rows x 35 columns]

In [49]:
# iloc is not usually used- we should subset on the basis of conditions or column names
df1[(df1['SEX']== 'FEMALE') & (df1['Age'] > 30.0)].head()

ID   Age  Customer_type  Gross_income   Net_income      SEX  \
2    2  38.0       SALARIED      1,50,000       30,000   FEMALE   
3    2  38.0       SALARIED      1,50,000       30,000   FEMALE   
24  13  33.0  SELF EMPLOYED        33,333       33,333   FEMALE   
25  13  33.0  SELF EMPLOYED        33,333       33,333   FEMALE   
48  25  34.0  SELF EMPLOYED      2,08,333     2,08,333   FEMALE   

   Type_of_industry Marital_Status  Months_in_city  Months_in_current_job  \
2            OTHERS        MARRIED             0.0                    120   
3            OTHERS        MARRIED             0.0                    120   
24           OTHERS        MARRIED           384.0                     77   
25           OTHERS        MARRIED           384.0                     77   
48           OTHERS        MARRIED           300.0                    120   

    ... ACCOUNT_12  ACCOUNT_13  ACCOUNT_14  ACCOUNT_15  ACCOUNT_16  \
2   ...          4           0           3           2           0   
3   ...          4           0           3           2           0   
24  ...          2           1           1           2           1   
25  ...          2           1           1           2           1   
48  ...          6           1           2           5           1   

    ACCOUNT_17  ACCOUNT_18  ACCOUNT_19  ACCOUNT_20  ACCOUNT_21  
2            2       10380           0       10380         124  
3            2       10380           0       10380         124  
24           1     2999109     2999109           0         181  
25           1     2999109     2999109           0         181  
48           2     2456287     2456287           0         490  

[5 rows x 35 columns]

In [56]:
# using a different condition
x = df1[(df1['Customer_type']== 'SALARIED') & (df1['Months_in_city'] > 300.0)]

# you can check the no of results using shape
x.shape

(326, 35)

In [57]:
# column wise analysis
x['Age'].head()

6     26.0
7     26.0
40    40.0
41    40.0
80    29.0
Name: Age, dtype: float64

In [58]:
# to get values of various columns, use a list and it neednt be in the same order as the df
x[['Age','SEX','Customer_type']].head()

Age   SEX Customer_type
6   26.0  MALE      SALARIED
7   26.0  MALE      SALARIED
40  40.0  MALE      SALARIED
41  40.0  MALE      SALARIED
80  29.0  MALE      SALARIED

In [60]:
# to get only the searched columns
df1.loc[(df1['Customer_type']== 'SALARIED') & (df1['Months_in_city'] > 300.0), ['Customer_type','Months_in_city']].head()


Customer_type  Months_in_city
6       SALARIED           324.0
7       SALARIED           324.0
40      SALARIED           480.0
41      SALARIED           480.0
80      SALARIED           336.0

In [61]:
# using a different condition and specifying the columns we want in the result set
df1.loc[(df1['SEX']== 'FEMALE') & (df1['Age'] > 30.0),['Age','SEX','Customer_type']].head()

Age     SEX  Customer_type
2   38.0  FEMALE       SALARIED
3   38.0  FEMALE       SALARIED
24  33.0  FEMALE  SELF EMPLOYED
25  33.0  FEMALE  SELF EMPLOYED
48  34.0  FEMALE  SELF EMPLOYED

In [ ]:
# we can use a condition negatively using ~
# basically it will return all the entries where the condition is not satisfied
# however if one of two conditions is not satisfied it will still return them
df1.loc[~((df1['SEX']== 'FEMALE') & (df1['Age'] > 30.0)),['Age','SEX','Customer_type']].head()



In [72]:
# we can drop columns using column names - it will only temporarily drop so of we 
# want it without the column we need to store it in a variable.
df1.drop(['Target','Debt_ratio'], axis=1).head()

ID   Age  Customer_type  Gross_income   Net_income      SEX  \
0   1  42.0  SELF EMPLOYED        91,667       91,667     MALE   
1   1  42.0  SELF EMPLOYED        91,667       91,667     MALE   
2   2  38.0       SALARIED      1,50,000       30,000   FEMALE   
3   2  38.0       SALARIED      1,50,000       30,000   FEMALE   
4   3  36.0  SELF EMPLOYED      1,88,183     1,88,183     MALE   

  Type_of_industry Marital_Status  Months_in_city  Months_in_current_job  ...  \
0     CONSTRUCTION        MARRIED             0.0                     96  ...   
1     CONSTRUCTION        MARRIED             0.0                     96  ...   
2           OTHERS        MARRIED             0.0                    120  ...   
3           OTHERS        MARRIED             0.0                    120  ...   
4           OTHERS        MARRIED             0.0                      0  ...   

  ACCOUNT_12  ACCOUNT_13  ACCOUNT_14  ACCOUNT_15  ACCOUNT_16  ACCOUNT_17  \
0         13           0           5           3           0           3   
1         13           0           5           3           0           3   
2          4           0           3           2           0           2   
3          4           0           3           2           0           2   
4         30           2          21           8           1           7   

   ACCOUNT_18  ACCOUNT_19  ACCOUNT_20  ACCOUNT_21  
0     1837374           0     1837374        1657  
1     1837374           0     1837374        1657  
2       10380           0       10380         124  
3       10380           0       10380         124  
4     3445241     1536325     1908916        2534  

[5 rows x 33 columns]

In [74]:
# in order to permanently delete from the original dataframe
df1.drop(['Target','Debt_ratio'], axis=1, inplace=True)

# alternate way to drop would be
# df1 = df1.drop(['Target','Debt_ratio'], axis=1)

In [75]:
df1.columns

Index(['ID', 'Age', 'Customer_type', ' Gross_income ', ' Net_income ', 'SEX',
       'Type_of_industry', 'Marital_Status', 'Months_in_city',
       'Months_in_current_job', 'Org_Type', 'Bank_balance', 'ENQ_1', 'ENQ_2',
       'ENQ_3', 'ENQ_4', 'ENQ_5', 'ENQ_6', 'ENQ_7', 'ENQ_8', 'ACCOUNT_9',
       'ACCOUNT_10', 'ACCOUNT_11', 'ACCOUNT_12', 'ACCOUNT_13', 'ACCOUNT_14',
       'ACCOUNT_15', 'ACCOUNT_16', 'ACCOUNT_17', 'ACCOUNT_18', 'ACCOUNT_19',
       'ACCOUNT_20', 'ACCOUNT_21'],
      dtype='object')

In [6]:
# deleting columns - alternate
del  df1['ENQ_8']

In [7]:
df1.columns

Index(['ID', 'Age', 'Customer_type', ' Gross_income ', ' Net_income ', 'SEX',
       'Type_of_industry', 'Marital_Status', 'Months_in_city',
       'Months_in_current_job', 'Org_Type', 'Bank_balance', 'Debt_ratio',
       'Target', 'ENQ_1', 'ENQ_2', 'ENQ_3', 'ENQ_4', 'ENQ_5', 'ENQ_6', 'ENQ_7',
       'ACCOUNT_9', 'ACCOUNT_10', 'ACCOUNT_11', 'ACCOUNT_12', 'ACCOUNT_13',
       'ACCOUNT_14', 'ACCOUNT_15', 'ACCOUNT_16', 'ACCOUNT_17', 'ACCOUNT_18',
       'ACCOUNT_19', 'ACCOUNT_20', 'ACCOUNT_21'],
      dtype='object')

In [9]:
# creating a dataframe using the random package 

# first generate data 
age = np.random.choice([15, 20, 30, 45, 12, '10', 15, '34', 7, 'Missing'], 50)
fico = np.random.choice(['100-150', '150-200', '200-250', '250-300'],50)
city = np.random.choice(['Mumbai', 'Delhi', 'Chennai', 'Kolkata'],50)
ID = np.arange(50)
rating = np.random.choice(['Excellent', 'Good', 'Bad', 'Pathetic'], 50)
balance = np.random.choice([10000, 20000, 30000, np.nan, 50000, 60000], 50)
children = np.random.randint(high=5,low=0,size=(50,))



In [10]:
# create the dataframe
mydata = pd.DataFrame({'ID':ID,'age':age,'fico':fico,'city':city,'rating':rating,'balance':balance,'children':children})

In [16]:
# check data type
mydata.dtypes

ID            int64
age          object
fico         object
city         object
rating       object
balance     float64
children      int64
dtype: object

In [27]:
# changing the data type of a column
mydata['age']=pd.to_numeric(mydata['age'],errors='coerce')


In [28]:
# adding a column with a const value
mydata['const_var'] = 100

In [30]:
# apply functions on the entire column
mydata['balance_log'] = np.log(mydata['balance'])

In [31]:
# creating a new column with a given function
mydata['age_children_ratio'] = mydata['age'] / mydata['children']

In [32]:
# checking for null values in a column
mydata['age'].isnull().head()

0    False
1    False
2    False
3    False
4     True
Name: age, dtype: bool

In [33]:
# identify locations where data is null
mydata.loc[mydata['age'].isnull(), 'age']

4    NaN
11   NaN
12   NaN
35   NaN
Name: age, dtype: float64

In [34]:
# changing null values with mean or median age
mydata.loc[mydata['age'].isnull(), 'age'] = np.mean(mydata['age'])

In [36]:
# cheaking the changes
mydata['age']

0     45.000000
1     20.000000
2     45.000000
3     34.000000
4     19.956522
5     34.000000
6     10.000000
7     20.000000
8      7.000000
9     15.000000
10    12.000000
11    19.956522
12    19.956522
13    45.000000
14     7.000000
15    20.000000
16    10.000000
17    20.000000
18     7.000000
19    10.000000
20    45.000000
21    10.000000
22     7.000000
23    15.000000
24    30.000000
25    34.000000
26    12.000000
27    45.000000
28    10.000000
29    34.000000
30    34.000000
31    12.000000
32    30.000000
33    12.000000
34    15.000000
35    19.956522
36    10.000000
37    10.000000
38    30.000000
39    34.000000
40     7.000000
41    10.000000
42    20.000000
43     7.000000
44    10.000000
45    20.000000
46    15.000000
47    12.000000
48    12.000000
49    15.000000
Name: age, dtype: float64

In [37]:
# adding or modifying a column based on conditions - where values are not set will default to 0

mydata['rating_score'] = np.where(mydata['rating'].isin(['good','Excellent']), 1, 0)

In [38]:
mydata.head()

ID        age     fico     city rating  balance  children  const_var  \
0   0  45.000000  250-300   Mumbai    Bad  60000.0         1        100   
1   1  20.000000  200-250    Delhi    Bad  20000.0         3        100   
2   2  45.000000  150-200   Mumbai   Good  30000.0         0        100   
3   3  34.000000  250-300  Kolkata    Bad  20000.0         3        100   
4   4  19.956522  250-300  Chennai   Good  60000.0         2        100   

   balance_log  age_children_ratio  rating_score  
0    11.002100           45.000000             0  
1     9.903488            6.666667             0  
2    10.308953                 inf             0  
3     9.903488           11.333333             0  
4    11.002100                 NaN             0

In [41]:
# alternate way of doing above using loc - - where values are not set will default to 0
mydata.loc[mydata['rating']=='Pathetic', 'rating_score'] = -1

In [42]:
# checking the above changes
mydata

ID        age     fico     city     rating  balance  children  const_var  \
0    0  45.000000  250-300   Mumbai        Bad  60000.0         1        100   
1    1  20.000000  200-250    Delhi        Bad  20000.0         3        100   
2    2  45.000000  150-200   Mumbai       Good  30000.0         0        100   
3    3  34.000000  250-300  Kolkata        Bad  20000.0         3        100   
4    4  19.956522  250-300  Chennai       Good  60000.0         2        100   
5    5  34.000000  200-250  Kolkata   Pathetic  30000.0         1        100   
6    6  10.000000  150-200  Chennai   Pathetic  20000.0         2        100   
7    7  20.000000  100-150   Mumbai       Good  20000.0         4        100   
8    8   7.000000  100-150   Mumbai   Pathetic      NaN         0        100   
9    9  15.000000  150-200    Delhi        Bad  20000.0         1        100   
10  10  12.000000  200-250  Kolkata        Bad      NaN         3        100   
11  11  19.956522  200-250  Kolkata       Good  50000.0         3        100   
12  12  19.956522  200-250  Kolkata        Bad  30000.0         4        100   
13  13  45.000000  100-150    Delhi   Pathetic      NaN         0        100   
14  14   7.000000  250-300  Chennai        Bad  20000.0         1        100   
15  15  20.000000  250-300   Mumbai   Pathetic  10000.0         2        100   
16  16  10.000000  250-300   Mumbai  Excellent  10000.0         0        100   
17  17  20.000000  150-200  Chennai        Bad  30000.0         0        100   
18  18   7.000000  250-300   Mumbai        Bad  50000.0         4        100   
19  19  10.000000  200-250  Chennai   Pathetic  60000.0         1        100   
20  20  45.000000  250-300    Delhi  Excellent  50000.0         3        100   
21  21  10.000000  150-200  Chennai  Excellent  10000.0         0        100   
22  22   7.000000  200-250  Kolkata       Good      NaN         4        100   
23  23  15.000000  250-300  Chennai   Pathetic  20000.0         0        100   
24  24  30.000000  200-250  Kolkata       Good  50000.0         2        100   
25  25  34.000000  150-200  Chennai       Good  20000.0         3        100   
26  26  12.000000  200-250  Chennai        Bad  20000.0         2        100   
27  27  45.000000  100-150   Mumbai   Pathetic  20000.0         1        100   
28  28  10.000000  250-300  Kolkata   Pathetic      NaN         3        100   
29  29  34.000000  250-300    Delhi  Excellent  20000.0         3        100   
30  30  34.000000  250-300  Chennai       Good  50000.0         4        100   
31  31  12.000000  150-200   Mumbai   Pathetic      NaN         1        100   
32  32  30.000000  100-150  Kolkata        Bad  50000.0         1        100   
33  33  12.000000  150-200  Kolkata       Good  30000.0         0        100   
34  34  15.000000  150-200    Delhi   Pathetic  50000.0         0        100   
35  35  19.956522  100-150   Mumbai        Bad  60000.0         1        100   
36  36  10.000000  100-150  Kolkata  Excellent  60000.0         4        100   
37  37  10.000000  250-300    Delhi        Bad  10000.0         0        100   
38  38  30.000000  100-150  Chennai        Bad      NaN         1        100   
39  39  34.000000  100-150   Mumbai        Bad  60000.0         4        100   
40  40   7.000000  150-200    Delhi       Good  60000.0         0        100   
41  41  10.000000  200-250    Delhi   Pathetic      NaN         2        100   
42  42  20.000000  100-150   Mumbai        Bad  30000.0         2        100   
43  43   7.000000  200-250  Kolkata       Good  60000.0         4        100   
44  44  10.000000  150-200  Chennai  Excellent  60000.0         2        100   
45  45  20.000000  200-250   Mumbai   Pathetic  10000.0         4        100   
46  46  15.000000  100-150    Delhi  Excellent  10000.0         0        100   
47  47  12.000000  200-250    Delhi  Excellent      NaN         2        100   
48  48  12.000000  150-200  Kolkata   Pathetic  50000.0         3        100   
49  

In [43]:
# we split range values, first we convert to string then 
# split it to two values, this will only separate the values, in order
# to split into two columns we use expand
mydata['fico'].str.split("-", expant=True).head()

# this just splits the fico column in the df and makes it a list of two values
mydata.head()


0    [250, 300]
1    [200, 250]
2    [150, 200]
3    [250, 300]
4    [250, 300]
Name: fico, dtype: object

In [44]:
# and we split and make it a float, since we have split strings saving it in k
k = mydata['fico'].str.split('-', expand=True).astype(float)
# K will be saved as a data frame 
k

0      1
0   250.0  300.0
1   200.0  250.0
2   150.0  200.0
3   250.0  300.0
4   250.0  300.0
5   200.0  250.0
6   150.0  200.0
7   100.0  150.0
8   100.0  150.0
9   150.0  200.0
10  200.0  250.0
11  200.0  250.0
12  200.0  250.0
13  100.0  150.0
14  250.0  300.0
15  250.0  300.0
16  250.0  300.0
17  150.0  200.0
18  250.0  300.0
19  200.0  250.0
20  250.0  300.0
21  150.0  200.0
22  200.0  250.0
23  250.0  300.0
24  200.0  250.0
25  150.0  200.0
26  200.0  250.0
27  100.0  150.0
28  250.0  300.0
29  250.0  300.0
30  250.0  300.0
31  150.0  200.0
32  100.0  150.0
33  150.0  200.0
34  150.0  200.0
35  100.0  150.0
36  100.0  150.0
37  250.0  300.0
38  100.0  150.0
39  100.0  150.0
40  150.0  200.0
41  200.0  250.0
42  100.0  150.0
43  200.0  250.0
44  150.0  200.0
45  200.0  250.0
46  100.0  150.0
47  200.0  250.0
48  150.0  200.0
49  200.0  250.0

In [46]:
# we use the k vlalues to add them to mydata 
mydata['f1'], mydata['f2'] = k[0], k[1]
mydata

ID        age     fico     city     rating  balance  children  const_var  \
0    0  45.000000  250-300   Mumbai        Bad  60000.0         1        100   
1    1  20.000000  200-250    Delhi        Bad  20000.0         3        100   
2    2  45.000000  150-200   Mumbai       Good  30000.0         0        100   
3    3  34.000000  250-300  Kolkata        Bad  20000.0         3        100   
4    4  19.956522  250-300  Chennai       Good  60000.0         2        100   
5    5  34.000000  200-250  Kolkata   Pathetic  30000.0         1        100   
6    6  10.000000  150-200  Chennai   Pathetic  20000.0         2        100   
7    7  20.000000  100-150   Mumbai       Good  20000.0         4        100   
8    8   7.000000  100-150   Mumbai   Pathetic      NaN         0        100   
9    9  15.000000  150-200    Delhi        Bad  20000.0         1        100   
10  10  12.000000  200-250  Kolkata        Bad      NaN         3        100   
11  11  19.956522  200-250  Kolkata       Good  50000.0         3        100   
12  12  19.956522  200-250  Kolkata        Bad  30000.0         4        100   
13  13  45.000000  100-150    Delhi   Pathetic      NaN         0        100   
14  14   7.000000  250-300  Chennai        Bad  20000.0         1        100   
15  15  20.000000  250-300   Mumbai   Pathetic  10000.0         2        100   
16  16  10.000000  250-300   Mumbai  Excellent  10000.0         0        100   
17  17  20.000000  150-200  Chennai        Bad  30000.0         0        100   
18  18   7.000000  250-300   Mumbai        Bad  50000.0         4        100   
19  19  10.000000  200-250  Chennai   Pathetic  60000.0         1        100   
20  20  45.000000  250-300    Delhi  Excellent  50000.0         3        100   
21  21  10.000000  150-200  Chennai  Excellent  10000.0         0        100   
22  22   7.000000  200-250  Kolkata       Good      NaN         4        100   
23  23  15.000000  250-300  Chennai   Pathetic  20000.0         0        100   
24  24  30.000000  200-250  Kolkata       Good  50000.0         2        100   
25  25  34.000000  150-200  Chennai       Good  20000.0         3        100   
26  26  12.000000  200-250  Chennai        Bad  20000.0         2        100   
27  27  45.000000  100-150   Mumbai   Pathetic  20000.0         1        100   
28  28  10.000000  250-300  Kolkata   Pathetic      NaN         3        100   
29  29  34.000000  250-300    Delhi  Excellent  20000.0         3        100   
30  30  34.000000  250-300  Chennai       Good  50000.0         4        100   
31  31  12.000000  150-200   Mumbai   Pathetic      NaN         1        100   
32  32  30.000000  100-150  Kolkata        Bad  50000.0         1        100   
33  33  12.000000  150-200  Kolkata       Good  30000.0         0        100   
34  34  15.000000  150-200    Delhi   Pathetic  50000.0         0        100   
35  35  19.956522  100-150   Mumbai        Bad  60000.0         1        100   
36  36  10.000000  100-150  Kolkata  Excellent  60000.0         4        100   
37  37  10.000000  250-300    Delhi        Bad  10000.0         0        100   
38  38  30.000000  100-150  Chennai        Bad      NaN         1        100   
39  39  34.000000  100-150   Mumbai        Bad  60000.0         4        100   
40  40   7.000000  150-200    Delhi       Good  60000.0         0        100   
41  41  10.000000  200-250    Delhi   Pathetic      NaN         2        100   
42  42  20.000000  100-150   Mumbai        Bad  30000.0         2        100   
43  43   7.000000  200-250  Kolkata       Good  60000.0         4        100   
44  44  10.000000  150-200  Chennai  Excellent  60000.0         2        100   
45  45  20.000000  200-250   Mumbai   Pathetic  10000.0         4        100   
46  46  15.000000  100-150    Delhi  Excellent  10000.0         0        100   
47  47  12.000000  200-250    Delhi  Excellent      NaN         2        100   
48  48  12.000000  150-200  Kolkata   Pathetic  50000.0         3        100   
49  

In [ ]:
# having added fico 1 and 2 we dont need the fico column so we can delete it
# del mydata['fico']


In [48]:
# check the unique values
mydata['city'].unique()

array(['Mumbai', 'Delhi', 'Kolkata', 'Chennai'], dtype=object)

In [ ]:
# we can get count of variables
mydata['city'].nunique()



In [53]:
# creating flag values or dummies where if its true we get 1 else we get 0
mydata['city_mumbai'] = np.where(mydata['city'] == 'Mumbai', 1,0)
mydata.head()

ID        age     fico     city rating  balance  children  const_var  \
0   0  45.000000  250-300   Mumbai    Bad  60000.0         1        100   
1   1  20.000000  200-250    Delhi    Bad  20000.0         3        100   
2   2  45.000000  150-200   Mumbai   Good  30000.0         0        100   
3   3  34.000000  250-300  Kolkata    Bad  20000.0         3        100   
4   4  19.956522  250-300  Chennai   Good  60000.0         2        100   

   balance_log  age_children_ratio  rating_score     f1     f2  city_mumbai  
0    11.002100           45.000000             0  250.0  300.0            1  
1     9.903488            6.666667             0  200.0  250.0            0  
2    10.308953                 inf             0  150.0  200.0            1  
3     9.903488           11.333333             0  250.0  300.0            0  
4    11.002100                 NaN             0  250.0  300.0            0

In [56]:
# alternate way of creating flag variable, we get 1 sic=nce the right hand evaluates to true
mydata['city_chennai'] = (mydata['city']=='Chennai').astype(int)
mydata.head()

ID        age     fico     city rating  balance  children  const_var  \
0   0  45.000000  250-300   Mumbai    Bad  60000.0         1        100   
1   1  20.000000  200-250    Delhi    Bad  20000.0         3        100   
2   2  45.000000  150-200   Mumbai   Good  30000.0         0        100   
3   3  34.000000  250-300  Kolkata    Bad  20000.0         3        100   
4   4  19.956522  250-300  Chennai   Good  60000.0         2        100   

   balance_log  age_children_ratio  rating_score     f1     f2  city_mumbai  \
0    11.002100           45.000000             0  250.0  300.0            1   
1     9.903488            6.666667             0  200.0  250.0            0   
2    10.308953                 inf             0  150.0  200.0            1   
3     9.903488           11.333333             0  250.0  300.0            0   
4    11.002100                 NaN             0  250.0  300.0            0   

   city_chennai  
0             0  
1             0  
2             0  
3             0  
4             1

In [60]:
# we then create for the 3rd value
# we must always create n-1 flag variables since the last variable will be all 0 
# which the ml algorith can identify
# having created dummy variables the main city column can be dropped
mydata['city_kolkata'] = np.where(mydata['city'] == 'Kolkata', 1,0)
mydata.head()

ID        age     fico     city rating  balance  children  const_var  \
0   0  45.000000  250-300   Mumbai    Bad  60000.0         1        100   
1   1  20.000000  200-250    Delhi    Bad  20000.0         3        100   
2   2  45.000000  150-200   Mumbai   Good  30000.0         0        100   
3   3  34.000000  250-300  Kolkata    Bad  20000.0         3        100   
4   4  19.956522  250-300  Chennai   Good  60000.0         2        100   

   balance_log  age_children_ratio  rating_score     f1     f2  city_mumbai  \
0    11.002100           45.000000             0  250.0  300.0            1   
1     9.903488            6.666667             0  200.0  250.0            0   
2    10.308953                 inf             0  150.0  200.0            1   
3     9.903488           11.333333             0  250.0  300.0            0   
4    11.002100                 NaN             0  250.0  300.0            0   

   city_chennai  city_kolkata  
0             0             0  
1             0             0  
2             0             0  
3             0             1  
4             1             0

In [67]:
# we can now delete the city column since we have created the dummies/flags

# another way to get dummies is forst create dummies then append to my data

print(mydata['rating'].unique())
print(mydata['rating'].nunique())

['Bad' 'Good' 'Pathetic' 'Excellent']
4


In [62]:
# we drop first column since we want n-1 dummies, prefix keeps the strat of the column name as assigned
dummy = pd.get_dummies(mydata['rating'], drop_first=True, prefix='rating')

dummy.head()



rating_Excellent  rating_Good  rating_Pathetic
0                 0            0                0
1                 0            0                0
2                 0            1                0
3                 0            0                0
4                 0            1                0

In [63]:
# we can concatenate one data frame to another 

mydata = pd.concat([mydata,dummy],axis=1)


In [64]:
mydata.head()


ID        age     fico     city rating  balance  children  const_var  \
0   0  45.000000  250-300   Mumbai    Bad  60000.0         1        100   
1   1  20.000000  200-250    Delhi    Bad  20000.0         3        100   
2   2  45.000000  150-200   Mumbai   Good  30000.0         0        100   
3   3  34.000000  250-300  Kolkata    Bad  20000.0         3        100   
4   4  19.956522  250-300  Chennai   Good  60000.0         2        100   

   balance_log  age_children_ratio  rating_score     f1     f2  city_mumbai  \
0    11.002100           45.000000             0  250.0  300.0            1   
1     9.903488            6.666667             0  200.0  250.0            0   
2    10.308953                 inf             0  150.0  200.0            1   
3     9.903488           11.333333             0  250.0  300.0            0   
4    11.002100                 NaN             0  250.0  300.0            0   

   city_chennai  city_kolkata  rating_Excellent  rating_Good  rating_Pathetic  
0             0             0                 0            0                0  
1             0             0                 0            0                0  
2             0             0                 0            1                0  
3             0             1                 0            0                0  
4             1             0                 0            1                0

In [69]:
# sorting and merging dataframes

df= pd.DataFrame(np.random.randint(2,8,(20,4)), columns=['A', 'B', 'C','D'])

df.head()


A  B  C  D
0  2  6  3  2
1  5  5  7  3
2  6  2  7  6
3  7  3  6  5
4  3  5  2  5

In [70]:
# sorting one or more columns in ascending or descing order, this will onlt
# sort the value temporarily and dosent modify the data frame
df.sort_values('A').head()
    


A  B  C  D
0   2  6  3  2
18  2  4  7  4
17  3  5  2  6
15  3  7  6  7
4   3  5  2  5

In [77]:
# to modify the df we have two options
# one
df = df.sort_values('A')
df


A  B  C  D
0   2  6  3  2
18  2  4  7  4
17  3  5  2  6
15  3  7  6  7
4   3  5  2  5

In [73]:
 # alternatively we can use sort_values function
df.sort_values('A', inplace=True)
df.head()

A  B  C  D
0   2  6  3  2
18  2  4  7  4
17  3  5  2  6
15  3  7  6  7
4   3  5  2  5

In [80]:
# to sort in descending manner
df.sort_values('A', inplace=True, ascending = False)
df.head()

A  B  C  D
17  3  5  2  6
15  3  7  6  7
4   3  5  2  5
0   2  6  3  2
18  2  4  7  4

In [81]:
# to sort multiple columns
df.sort_values(['B', 'C'], ascending=[True,False])
df.head()

A  B  C  D
17  3  5  2  6
15  3  7  6  7
4   3  5  2  5
0   2  6  3  2
18  2  4  7  4

In [4]:
# stacking / combining data frames by rows - tis will duplocate the row indices
df1 = pd.DataFrame([['a', 1], ['b', 2]], columns= ['letter','number'])
df2 = pd.DataFrame([['a', 1, 'cat'], ['b', 2, 'dog']], columns= ['letter','number', 'animal'])
pd.concat([df1,df2], axis = 0)

letter  number animal
0      a       1    NaN
1      b       2    NaN
0      a       1    cat
1      b       2    dog

In [5]:
# this will help prevent duplication of indices
pd.concat([df1,df2], axis = 0, ignore_index=True)

letter  number animal
0      a       1    NaN
1      b       2    NaN
2      a       1    cat
3      b       2    dog

In [ ]:
# to combine data frames using columns
df1 = pd.DataFrame([['tiger', 'leo'], ['lion', 'busa'], ['cheetah', 'rex']], columns= ['animal','name'])
df2 = pd.DataFrame([['a', 1, 'cat'], ['b', 2, 'dog']], columns= ['letter','number', 'animal'])
pd.concat([df1,df2], axis = 0)

In [10]:
# merging data frames like sql joins

df1=pd.DataFrame({'cust_id':[1,2,3,4,5],'product':['radio','pen','pencil','eraser','mobile']})
df2=pd.DataFrame({'cust_id':[3,4,5,6,7],'state':['MH','MH','GJ','MP','UP']})

df1
df2

cust_id state
0        3    MH
1        4    MH
2        5    GJ
3        6    MP
4        7    UP

In [7]:
# right join will give all the columns from the right table
pd.merge(df1,df2,on=['cust_id'],how='right')

cust_id product state
0        3  pencil    MH
1        4  eraser    MH
2        5  mobile    GJ
3        6     NaN    MP
4        7     NaN    UP

In [8]:
# left join will give all the columns from the left table
pd.merge(df1,df2,on=['cust_id'],how='left')

cust_id product state
0        1   radio   NaN
1        2     pen   NaN
2        3  pencil    MH
3        4  eraser    MH
4        5  mobile    GJ

In [9]:
# inner join will give all the commmon columns from both tables
pd.merge(df1,df2,on=['cust_id'],how='inner')

cust_id product state
0        3  pencil    MH
1        4  eraser    MH
2        5  mobile    GJ

In [11]:
# use r before the path so that data is read as a raw file - importing bank data
file=r'~/Documents/SDBI/Python/bank-full.csv'

In [12]:
# reading the bank data file
bd = pd.read_csv(file)

In [15]:
# view the top few rows of data
bd.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome Target  
0  unknown    5   may       261         1     -1         0  unknown     no  
1  unknown    5   may       151         1     -1         0  unknown     no  
2  unknown    5   may        76         1     -1         0  unknown     no  
3  unknown    5   may        92         1     -1         0  unknown     no  
4  unknown    5   may       198         1     -1         0  unknown     no

In [13]:
# describe allows us to have a numerical summary of the data
bd.describe()

age        balance           day      duration      campaign  \
count  45211.000000   45211.000000  45211.000000  45211.000000  45211.000000   
mean      40.936210    1362.272058     15.806419    258.163080      2.763841   
std       10.618762    3044.765829      8.322476    257.527812      3.098021   
min       18.000000   -8019.000000      1.000000      0.000000      1.000000   
25%       33.000000      72.000000      8.000000    103.000000      1.000000   
50%       39.000000     448.000000     16.000000    180.000000      2.000000   
75%       48.000000    1428.000000     21.000000    319.000000      3.000000   
max       95.000000  102127.000000     31.000000   4918.000000     63.000000   

              pdays      previous  
count  45211.000000  45211.000000  
mean      40.197828      0.580323  
std      100.128746      2.303441  
min       -1.000000      0.000000  
25%       -1.000000      0.000000  
50%       -1.000000      0.000000  
75%       -1.000000      0.000000  
max      871.000000    275.000000

In [18]:
# gives us the no of unique values per variable
bd.nunique()

age            77
job            12
marital         3
education       4
default         2
balance      7168
housing         2
loan            2
contact         3
day            31
month          12
duration     1573
campaign       48
pdays         559
previous       41
poutcome        4
Target          2
dtype: int64

In [22]:
# we can also use describe() to get the summary and stats for an individual column

bd['age'].describe()


count    45211.000000
mean        40.936210
std         10.618762
min         18.000000
25%         33.000000
50%         39.000000
75%         48.000000
max         95.000000
Name: age, dtype: float64

In [23]:
bd['job'].describe()

count           45211
unique             12
top       blue-collar
freq             9732
Name: job, dtype: object

In [24]:
# does as the function suggests - distribution- there are many such inbuilt statistical functions

bd['age'].mean(), bd['age'].median()

(40.93621021432837, 39.0)

In [ ]:
# we get the count of value for the individual colums
k = bd['job'].value_counts()
k

In [27]:
k.values

array([9732, 9458, 7597, 5171, 4154, 2264, 1579, 1487, 1303, 1240,  938,
        288])

In [30]:
# will return categories of values with frequency greater than 1500
k.index[k.values>1500]

Index(['blue-collar', 'management', 'technician', 'admin.', 'services',
       'retired', 'self-employed'],
      dtype='object')

In [31]:
k.index[-1] # return the category with lowest count

'unknown'

In [34]:
k.index[0] # return the category with highest count

'blue-collar'

In [33]:
k.index[-2] # return the category with second lowest count

'student'

In [32]:
# crosstab gives a tabular result for the columns asked for
pd.crosstab(bd['age'],bd['job'])

job  admin.  blue-collar  entrepreneur  housemaid  management  retired  \
age                                                                      
18        0            0             0          0           0        0   
19        0            0             0          0           0        0   
20        2            4             0          0           0        0   
21        5           14             1          0           2        0   
22       14           15             0          2           6        0   
..      ...          ...           ...        ...         ...      ...   
90        0            0             0          0           0        2   
92        0            0             0          0           0        2   
93        0            0             0          0           0        2   
94        0            0             0          0           0        1   
95        0            0             0          0           0        2   

job  self-employed  services  student  technician  unemployed  unknown  
age                                                                     
18               0         0       12           0           0        0  
19               0         0       35           0           0        0  
20               0         1       43           0           0        0  
21               0         4       46           4           3        0  
22               2        18       63           8           1        0  
..             ...       ...      ...         ...         ...      ...  
90               0         0        0           0           0        0  
92               0         0        0           0           0        0  
93               0         0        0           0           0        0  
94               0         0        0           0           0        0  
95               0         0        0           0           0        0  

[77 rows x 12 columns]